#!/bin/bash

./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-nnns --output_dir=./out-nnns-mtl84-marian-en-de/ --model_name_or_path=Helsinki-NLP/opus-mt-en-de;
./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-nnns --output_dir=./out-nnns-mtl84-bart-base/ --model_name_or_path=facebook/bart-base;
./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-nnns --output_dir=./out-nnns-mtl84-t5-base/ --model_name_or_path=t5-base --train_batch_size=4 --eval_batch_size=4 --max_source_length=512;

./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-nnws --output_dir=./out-nnws-mtl84-marian-en-de/ --model_name_or_path=Helsinki-NLP/opus-mt-en-de;
./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-nnws --output_dir=./out-nnws-mtl84-bart-base/ --model_name_or_path=facebook/bart-base;
./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-nnws --output_dir=./out-nnws-mtl84-t5-base/ --model_name_or_path=t5-base --train_batch_size=4 --eval_batch_size=4 --max_source_length=512;

./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-wnws --output_dir=./out-wnws-mtl84-marian-en-de/ --model_name_or_path=Helsinki-NLP/opus-mt-en-de;
./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-wnws --output_dir=./out-wnws-mtl84-bart-base/ --model_name_or_path=facebook/bart-base;
./finetune.py --learning_rate=3e-5 --gpus=0 --do_train --do_predict --n_val=1000 --val_check_interval=0.1 --logger_name=wandb --task=translation --early_stopping_patience=10 --max_target_length=84 --data_dir=./ttf-wnws --output_dir=./out-wnws-mtl84-t5-base/ --model_name_or_path=t5-base --train_batch_size=4 --eval_batch_size=4 --max_source_length=512;